name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Docker Compose
        run: |
          docker-compose --version
          
      - name: Build Docker container
        run: |
          docker-compose build

      - name: Install dependencies
        run: |
          docker-compose run python-app make install

      - name: Run Linter
        run: |
          docker-compose run python-app make lint

      - name: Run Tests
        run: |
          docker-compose run python-app make test

      - name: Commit changes (if any)
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto commit from GitHub Actions" || echo "No changes to commit"
          git push
