name: CI Pipeline for my-ml-project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint code with pylint
      run: |
        pylint --disable=R,C *.py

    - name: Format code with black
      run: |
        black --check *.py

    - name: Run tests with pytest
      run: |
        pytest -vv --maxfail=1

    - name: Build Docker image
      run: |
        docker-compose build

    - name: Run Docker container
      run: |
        docker-compose run python-app python predict.py

    - name: Push Docker image to registry (optional)
      if: github.ref == 'refs/heads/main'
      run: |
        docker tag my-python-app:latest mydockerhubusername/my-python-app:latest
        docker push mydockerhubusername/my-python-app:latest
